### ISSUE TITLE
Check vowels

### ISSUE THREAD

**Issue by shorodilov** [edu-python-course/problem-sets#93]
Get a character from the user.
Print out **vowel check result**.

**Comment by Rishitha-VasiReddy** [comment]
Hi @shorodilov, can you please assign this issue to me. I would like to work on it.

**Comment by shorodilov** [comment]
> Hi @shorodilov, can you please assign this issue to me. I would like to work on it.

Done

**Comment by shorodilov** [comment]
@Rishitha-VasiReddy just let me know in case you need some more "info" or help.
We are the open source community :-)
I'll do my best to provide you all the materials you need.

**Comment by Rishitha-VasiReddy** [comment]
Hi @shorodilov, I've created a PR for this issue. Please review
